// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/fallguysskyboxbk.tga
gfx/env/fallguysskyboxdn.tga
gfx/env/fallguysskyboxft.tga
gfx/env/fallguysskyboxlf.tga
gfx/env/fallguysskyboxrt.tga
gfx/env/fallguysskyboxup.tga
sound/fallguys/bell.ogg
sound/fallguys/bellpitch.ogg
sound/fallguys/bodyhit.ogg
sound/fallguys/bounce.ogg
sound/fallguys/bounce2.ogg
sound/fallguys/bounce3.ogg
sound/fallguys/canonfire.ogg
sound/fallguys/canonfire2.ogg
sound/fallguys/canonfire3.ogg
sound/fallguys/countdown_go.wav
sound/fallguys/countdown_one.wav
sound/fallguys/countdown_three.wav
sound/fallguys/countdown_two.wav
sound/fallguys/drum.ogg
sound/fallguys/eliminated.wav
sound/fallguys/fruitappear.ogg
sound/fallguys/fruitdisappear.ogg
sound/fallguys/grab.ogg
sound/fallguys/grabrelease.ogg
sound/fallguys/impact1.ogg
sound/fallguys/impact2.ogg
sound/fallguys/impact3.ogg
sound/fallguys/intro.ogg
sound/fallguys/jump.ogg
sound/fallguys/jumpwater1.ogg
sound/fallguys/jumpwater2.ogg
sound/fallguys/jumpwater3.ogg
sound/fallguys/jumpwater4.ogg
sound/fallguys/loading.ogg
sound/fallguys/matchmaking.ogg
sound/fallguys/mecha.ogg
sound/fallguys/mfcountdown.ogg
sound/fallguys/mfcountdown2.ogg
sound/fallguys/mfdisappear.ogg
sound/fallguys/mfselect.ogg
sound/fallguys/percussionend.ogg
sound/fallguys/play.ogg
sound/fallguys/playerfall1.ogg
sound/fallguys/playerfall2.ogg
sound/fallguys/playerhit1.ogg
sound/fallguys/playerhit2.ogg
sound/fallguys/playerhit3.ogg
sound/fallguys/playerhit4.ogg
sound/fallguys/playerhit5.ogg
sound/fallguys/playerhit6.ogg
sound/fallguys/playerhit7.ogg
sound/fallguys/playerjump1.ogg
sound/fallguys/playerjump2.ogg
sound/fallguys/playerjump3.ogg
sound/fallguys/playerjump4.ogg
sound/fallguys/playerjump5.ogg
sound/fallguys/playerjump6.ogg
sound/fallguys/playerjump7.ogg
sound/fallguys/playerjump8.ogg
sound/fallguys/qualified.wav
sound/fallguys/race.ogg
sound/fallguys/reveal.ogg
sound/fallguys/rhinoattack.ogg
sound/fallguys/rhinoendattack.ogg
sound/fallguys/rhinoidle.ogg
sound/fallguys/rhinoloadattack.ogg
sound/fallguys/roundend.ogg
sound/fallguys/seesawstart.ogg
sound/fallguys/seesawstart2.ogg
sound/fallguys/seesawstart3.ogg
sound/fallguys/seesawstart4.ogg
sound/fallguys/seesawstop.ogg
sound/fallguys/seesawstop2.ogg
sound/fallguys/seesawstop3.ogg
sound/fallguys/slide.ogg
sound/fallguys/survival.ogg
sound/fallguys/win.ogg
sprites/fallguys/playerarrow.spr
sprites/fallguys/playerarrow2.spr
sprites/fallguys/eliminated.spr
sprites/fallguys/introdarkgreen.spr
sprites/fallguys/introlightgreen.spr
sprites/fallguys/introroxo.spr
sprites/fallguys/countdown.spr
sprites/fallguys/qualified.spr
sprites/fallguys/roundend.spr
sprites/fallguys/roundover.spr
sprites/fallguys/timer.spr
sprites/laserbeam.spr
sprites/boom.spr
models/fallguys/arch.mdl
models/fallguys/ball.mdl
models/fallguys/ball2.mdl
models/fallguys/banner.mdl
models/fallguys/barrier.mdl
models/fallguys/barrier2.mdl
models/fallguys/barrier3.mdl
models/fallguys/blade.mdl
models/fallguys/blade3.mdl
models/fallguys/bowl.mdl
models/fallguys/bplat.mdl
models/fallguys/btri.mdl
models/fallguys/bumper.mdl
models/fallguys/bumper2.mdl
models/fallguys/bumper3.mdl
models/fallguys/bumper5.mdl
models/fallguys/bumperbase.mdl
models/fallguys/cage.mdl
models/fallguys/canon.mdl
models/fallguys/drum.mdl
models/fallguys/drum2.mdl
models/fallguys/drum2rot.mdl
models/fallguys/flag.mdl
models/fallguys/flagbase.mdl
models/fallguys/hammer.mdl
models/fallguys/hexfloor.mdl
models/fallguys/hexwall.mdl
models/fallguys/logo.mdl
models/fallguys/logo2.mdl
models/fallguys/net7.mdl
models/fallguys/number.mdl
models/fallguys/pillar.mdl
models/fallguys/pole.mdl
models/fallguys/pole15.mdl
models/fallguys/pole16.mdl
models/fallguys/post.mdl
models/fallguys/rainbow.mdl
models/fallguys/rainbow2.mdl
models/fallguys/rainbow3.mdl
models/fallguys/rhino.mdl
models/fallguys/roll.mdl
models/fallguys/roll2.mdl
models/fallguys/roll3.mdl
models/fallguys/roll4.mdl
models/fallguys/scaff.mdl
models/fallguys/section.mdl
models/fallguys/section2.mdl
models/fallguys/seesaw.mdl
models/fallguys/stick.mdl
models/fallguys/water.mdl
models/fallguys/wball.mdl